# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/3c6d9722-e63c-4936-6a03-7c470ea8f9f0/volume/aggregate/webencodings-feedstock/recipe, last modified Fri Nov  8 02:13:36 2019
# ------------------------------------------------

package:
    name: webencodings
    version: 0.5.1
source:
    fn: webencodings-0.5.1.tar.gz
    sha256: 082367f568a7812aa5f6922ffe3d9d027cd83829dc32bcaac4c874eeed618000
    url: https://github.com/gsnedders/python-webencodings/archive/v0.5.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_1
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - webencodings
about:
    dev_url: https://github.com/gsnedders/python-webencodings
    doc_url: https://pythonhosted.org/webencodings
    home: https://github.com/gsnedders/python-webencodings
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Character encoding aliases for legacy web content
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
