# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b1f8ac43-0acf-4bad-7a4d-36e43f443342/volume/rsync-recipes/_ipyw_jlab_nb_ext_conf-0.1.0-python_3.8-on-osx, last modified Wed Apr 29 09:54:44 2020
# ------------------------------------------------

package:
    name: _ipyw_jlab_nb_ext_conf
    version: 0.1.0
build:
    always_include_files:
        - etc/jupyter/jupyter_notebook_config.json
        - etc/jupyter/nbconfig/notebook.json
    number: '0'
    string: py38_0
requirements:
    host:
        - appnope 0.1.0 py38_0
        - attrs 19.3.0 py_0
        - backcall 0.2.0 py_0
        - bleach 3.1.5 py_0
        - brotlipy 0.7.0 py38haf1e3a3_1000
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - cffi 1.14.0 py38hc512035_1
        - chardet 3.0.4 py38_1003
        - cryptography 2.9.2 py38ha12b0ac_0
        - decorator 4.4.2 py_0
        - defusedxml 0.6.0 py_0
        - entrypoints 0.3 py38_0
        - idna 2.10 py_0
        - importlib-metadata 1.7.0 py38_0
        - importlib_metadata 1.7.0 0
        - ipykernel 5.3.0 py38h5ca1d4c_0
        - ipython 7.16.1 py38h5ca1d4c_0
        - ipython_genutils 0.2.0 py38_0
        - ipywidgets 7.5.1 py_0
        - jedi 0.17.1 py38_0
        - jinja2 2.11.2 py_0
        - json5 0.9.5 py_0
        - jsonschema 3.2.0 py38_0
        - jupyter_client 6.1.3 py_0
        - jupyter_core 4.6.3 py38_0
        - jupyterlab 2.1.5 py_0
        - jupyterlab_server 1.1.5 py_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - libsodium 1.0.18 h1de35cc_0
        - markupsafe 1.1.1 py38h1de35cc_0
        - mistune 0.8.4 py38h1de35cc_1000
        - nbconvert 5.6.1 py38_0
        - nbformat 5.0.7 py_0
        - ncurses 6.2 h0a44026_1
        - notebook 6.0.3 py38_0
        - openssl 1.1.1g h1de35cc_0
        - packaging 20.4 py_0
        - pandoc 2.9.2.1 0
        - pandocfilters 1.4.2 py38_1
        - parso 0.7.0 py_0
        - pexpect 4.8.0 py38_0
        - pickleshare 0.7.5 py38_1000
        - prometheus_client 0.8.0 py_0
        - prompt-toolkit 3.0.5 py_0
        - ptyprocess 0.6.0 py38_0
        - pycparser 2.20 py_0
        - pygments 2.6.1 py_0
        - pyopenssl 19.1.0 py38_0
        - pyparsing 2.4.7 py_0
        - pyrsistent 0.16.0 py38h1de35cc_0
        - pysocks 1.7.1 py38_0
        - python 3.8.3 h26836e1_1
        - python-dateutil 2.8.1 py_0
        - pyzmq 19.0.1 py38hb1e8313_1
        - readline 8.0 h1de35cc_0
        - requests 2.24.0 py_0
        - send2trash 1.5.0 py38_0
        - setuptools 47.3.1 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 hffcf06c_0
        - terminado 0.8.3 py38_0
        - testpath 0.4.4 py_0
        - tk 8.6.10 hb0a8c7a_0
        - tornado 6.0.4 py38h1de35cc_1
        - traitlets 4.3.3 py38_0
        - urllib3 1.25.9 py_0
        - wcwidth 0.2.5 py_0
        - webencodings 0.5.1 py38_1
        - widgetsnbextension 3.5.1 py38_0
        - xz 5.2.5 h1de35cc_0
        - zeromq 4.3.2 hb1e8313_2
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - ipywidgets
        - jupyterlab
        - python >=3.8,<3.9.0a0
        - widgetsnbextension
test:
    commands:
        - jupyter-nbextension list
        - jupyter-serverextension list
about:
    home: https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config
    license: BSD
    summary: A configuration metapackage for enabling Anaconda-bundled jupyter extensions
extra:
    copy_test_source_files: true
    final: true
